spring.application.name=Poseidon

logging.level.org.springframework=INFO

################### DataSource Configuration ##########################
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/poseidon
spring.datasource.username=root
spring.datasource.password=77:9R?h(Ndcgx8N-sY9M7E]/

################### Hibernate Configuration ##########################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
